# Workflow
# Should have a name
name: Hello-first

on:
  workflow_dispatch:
# Jobs
# Should be inside the workflow
jobs:
  say-hello:
    runs-on: ubuntu-latest 
    steps:
      - name: Say hello to everyone
        run: echo "Hello Sid"

  # IDK y it's not triggering
