# Workflow
name: Hello

# Controls when the workflow will run
on:
  workflow_dispatch:

# Defines the jobs to execute
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello to everyone
        run: echo "Hello Dosto"
